version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
  - Toolset: v140
  - Toolset: v120
  - Toolset: v110
  - Toolset: v100

platform:
  - Win32
  - x64

configuration:
  - Release
  - Debug

build:
  verbosity: detailed

build_script:
- cmd: |
    .\build_all.bat

